Build fix for DMX
./../dix/.libs/libdix.a(pixmap.o): In function `PixmapStartDirtyTracking':
xorg/xserver/dix/pixmap.c:194: undefined reference to `RRTransformCompute'

I'm not quite sure how 0db457b fixes this

Move RANDR_LIB to after DIX_LIB, so the reference to RRTransformCompute in
DIX_LIB is satisfied.

Signed-off-by: Jon TURNEY <jon.turney@dronecode.org.uk>