Fix implicit-function-declaration warning in DrawableGone() by adding a prototype for FlushContext()
glxext.c: In function 'DrawableGone':
glxext.c:142:13: error: implicit declaration of function 'FlushContext' [-Werror=implicit-function-declaration]
             FlushContext(c);
             ^

This is a follow-up patch to "glx: Flush context which is being made non-current due to the drawable going away"